merging release-7.44.0 to master
TEIC/Stylesheets pull request #327
Opened 2018-06-20 14:28 UTC by petrul

this change allows also the specification of the Author of the document by also using the 'Author' ODT Style (alternatively to the hard-to-access dc:initial-creator meta tag).

The 'Title' ODT Style is already used to allow the specification of the title of the document (alternatively to dc:title). This change extends the same logic for the Author.

(in libre office meta fields are either hard to access or downright missing in the GUI).

2018-06-20 18:21 UTC, peterstadler commented
I fear something went wrong with this PR as there are no changes to the code? Or am I missing something?

2018-06-27 10:28 UTC, peterstadler reviewed
I tested locally without any errors! That's the good news ;)
The bad news is, it seems there is some dependent issue with multiple authors? I'm not familiar with the odt format, but my guess it we should be able to support this (or restrict to one)?

2018-06-27 10:28 UTC, peterstadler commented on odt/odttotei.xsl
> +      <xsl:when test="$META/office:meta/meta:initial-creator">
To reproduce the old version you should probably only take the first `text:p[@text:style-name='Title']` (see old line 116), hence this should be `$META[1]/office:meta/meta:initial-creator`

2018-06-27 10:28 UTC, peterstadler commented on odt/odttotei.xsl
> +	    select="/office:document-content/office:body/office:text/text:p[@text:style-name='Author']"
I'm not familiar with the odt format but I guess there might be several authors (see also next comment). So it's probably safest to pick only the first `text:p[@text:style-name='Author']`. Or we need to iterate over the authors when outputting these …

2018-06-27 16:21 UTC, petrul commented on odt/odttotei.xsl
> +	    select="/office:document-content/office:body/office:text/text:p[@text:style-name='Author']"
Indeed the old version only picked the first 'Title'-styled paragraph. 

I see no reason for that. If the Title is streched on two lines, both should be taken.

Same rationale for the Author, especially given that one document might have several Authors

2018-06-27 19:13 UTC, peterstadler commented on odt/odttotei.xsl
> +	    select="/office:document-content/office:body/office:text/text:p[@text:style-name='Author']"
Yes, but within the resulting TEI document there should be an `<author>` element for every author name (not several names within one `<author>` element).
Could you add (and push) the appropriate `<xsl:for-each>` loop to your branch (so the pull request will be updated)?

2019-02-19 20:02 UTC, petrul commented
Hello again, sorry for the delay, I had completely forgotten XSLT.

As I had to dive again recently into this marvellous set of tags language, I could also fix your request to generate several <author> </author> elements inside the titleStmt, if there are several paragraphs in the .odt styled with 'Author'.

There are also a few additions, mainly taking care of special styles: Subtitle, Epigraph, Trailer etc which generate <p class="subtitle"> HTML elements.

2019-09-16 08:39 UTC, martindholmes commented
@peterstadler to go ahead, but look carefully at each individual change; for example, `<p class="subtitle">` seems a bit strange to me, unless I'm misunderstanding it.

2019-09-16 09:52 UTC, martinascholger commented
The Stylesheets group will have a look at it in the next meeting in October

2021-10-18 15:40 UTC, martindholmes commented
@sydb, @npcole and I looked at this today, and we believe that the original pull request has been severely muddied by additional commits to the same PR. It's also not clear whether @petrul did address @peterstadler's concerns about multiple authors, or the additional concern raised about multi-line titles. We suggest that each of these specific issues be raised as individual tickets and implemented.

2022-08-22 16:14 UTC, sydb requested changes

2022-08-22 16:14 UTC, sydb commented on odt/odttotei.xsl
> +    <binaryObject id="{generate-id()}" encoding="base64" mimeType="image/jpg">
@petrul — TEI does not have an `@id` attribute. You mean `@xml:id`, yes?

2022-08-22 17:05 UTC, petrul commented
Indeed, it would be the regular xml id attribute.

On Mon, Aug 22, 2022 at 7:15 PM Syd Bauman ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In odt/odttotei.xsl
> <https://github.com/TEIC/Stylesheets/pull/327#discussion_r951629422>:
>
> > @@ -877,7 +877,7 @@ of this software, even if advised of the possibility of such damage.
>
>    </xsl:template>
>
>
>
>    <xsl:template match="office:binary-data">
>
> -    <binaryObject encoding="base64" mimeType="image/jpg">
>
> +    <binaryObject id="{generate-id()}" encoding="base64" mimeType="image/jpg">
>
>
> @petrul <https://github.com/petrul> — TEI does not have an @id attribute.
> You mean @xml:id, yes?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TEIC/Stylesheets/pull/327#pullrequestreview-1080775641>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADRMLTDCBWT6NLM34VLGGTV2ORQVANCNFSM4FF5RONA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-25 08:39 UTC, petrul commented on odt/odttotei.xsl
> +    <binaryObject id="{generate-id()}" encoding="base64" mimeType="image/jpg">
for me it s a mystery why this commit ended up on this merge request, I just modified my own fork of tei-stylesheets and commited. I guess there's more to git than you can learn in a few years.

It these changes do not make sense for you, feel free to disregard this merge request.

2023-09-28 18:25 UTC, raffazizzi commented
We couldn't merge this PR, but we plan to implement this later on, see https://github.com/TEIC/Stylesheets/issues/625

2023-09-28 18:25 UTC, closed without merging