TEI to markdown improvements.
TEIC/Stylesheets pull request #432
Opened 2020-05-10 16:29 UTC by vvasuki

tei-to-markdown-sarit.xsl can be omitted - it is specific to the sarit database.

2021-11-04 19:21 UTC, peterstadler commented
@vvasuki  thank you for the PR! 
Since it's not up to date with our current dev branch and there's a merge conflict, may I ask you to rebase/update this PR so we can test it and eventually merge it?!

2021-11-07 12:53 UTC, vvasuki commented
Fixed merge conflict. To aid comparison modulo formatting changes - https://www.diffchecker.com/lSqcB5r9 or https://i.imgur.com/5kXtV3b.png

2021-11-07 17:02 UTC, peterstadler requested changes
Thanks for updating this PR and all your work!
Yet, there seems to be an invisible(?) regression since your https://github.com/sanskrit-coders/Stylesheets/blob/6d2d6ed61dccc1a3b6791f20981df7d10aa4b89f/markdown/tei-to-markdown.xsl#L297 is missing a whitespace after the "*". 
You can see that regression in our GitHub action tests at e.g. https://github.com/TEIC/Stylesheets/runs/4131270793

2021-11-07 17:02 UTC, peterstadler commented on markdown/tei-to-markdown.xsl
> +    <xsl:template match="note/p|ref">
This template rule `<xsl:template match="note/p|ref">` is not self explanatory to me. I would expect to wrap the whole `tei:note` into brackets, not every nested paragraph by itself? Second, a straight forward translation of `tei:ref[@target]` to would be `[Link text](URL)`.
So, while this code might fit your project encoding, I would hesitate to merge it into the TEIC's Stylesheets which aim to be as generic as possible.

2021-11-08 04:36 UTC, vvasuki commented on markdown/tei-to-markdown.xsl
> +    <xsl:template match="note/p|ref">
I have made it so. Please check. 

Attaching files which show the improvement.

[mdtest1.local.md](https://github.com/TEIC/Stylesheets/files/7494267/mdtest1.local.md)
[mdtest1.orig.local.md](https://github.com/TEIC/Stylesheets/files/7494268/mdtest1.orig.local.md)

2021-11-08 04:37 UTC, vvasuki commented
(Fixed the regression in list items.)

2022-07-01 02:33 UTC, sydb commented
@vvasuki —
Sorry this is taking so long. A few of us took a more careful look at this, and overall it looks great. But the change creates an error in the test procedure: the file expected-results/mdtest2.md is no longer what is expected. Can you fix that or would you like me to do that for you? (In which case you have to give me r/w access to your repo.)
Thank you!
P.S. Also probably a good idea to merge from TEIC/Stylesheets dev branch, again.

2022-07-01 02:51 UTC, vvasuki commented
@sydb It would be great if you could make the necessary changes yourself.
reg. rw access to my repo - you should have received a github invitation.

2022-07-01 14:18 UTC, sydb commented
Excellent. Update to Test/expected-results/ and Test2/expected-results/ made. This change now passes all tests in bot Test/ and Test2/. Note that I did not merge in the current TEIC:dev into this repo (only because I have forgotten the syntax).

On quick look I think it safe to say that this PR is not perfect (is missing lots of stuff it _could_ do, and there might even be some problems), but it is **so** much better than what we have now, I think it should be accepted and merged as soon as can reasonably be done.

2022-07-01 17:12 UTC, HelenaSabel commented
Tested locally. All tests passed thanks to change made per issue #560. 

However I cannot merge this PR (because the tests here have failed). Either @vvasuki pulls and merges the main Stylesheets repository to obtain the necessary file, or maybe @sydb can do it since he has push privileges in this fork. In any case, this is ready to merge

2022-07-01 21:34 UTC, sydb commented
Per @HelenaSabel comment above, latest Makefile tweaks have been merged in. The failures in the tests are problems with Slack notification, so I agree with her, this can be merged at will.

2022-07-22 15:11 UTC, merged