Sydb makefile in test dir
TEIC/Stylesheets pull request #455
Opened 2020-08-13 23:07 UTC by sydb

I _think_ this is ready to rock and roll. It has the new p5subset from TEI dev branch in it. All tests (in Test/) pass, as far as I can tell. (I have not tried Test2/ yet; maybe can do that after dinner.)

If one or two of you, the requested reviewers, can check out this branch and test the test procedure, that would be appreciated. If you `cd Stylesheets/Test` and then `make help` you will get some brief documentation.

2020-08-13 23:08 UTC, sydb commented
P.S. This means I do not know what went wrong with the build & test we tried at the Tue 11 Aug meeting, but that particular test is passing now.

2020-08-14 07:03 UTC, peterstadler commented
Thank you @sydb for all the work but it's really hard to review since you altered the build process, the source for the tests and the expected results at once. We now had a lot of reverse engineering to do if we wanted to really check this!

2020-08-14 07:11 UTC, peterstadler commented
I tried to run the tests with your modified Makefile against our current `p5subset.xml` and expected results in the dev branch. 

```
		then diff  -r  actual-results/testnotes/ expected-results/testnotes; fi
diff -r actual-results/testnotes/index.html expected-results/testnotes/index.html
13c13
<     <link href="../../../tei.css" rel="stylesheet" type="text/css" />
---
>     <link href="../../tei.css" rel="stylesheet" type="text/css" />
diff -r actual-results/testnotes/one.html expected-results/testnotes/one.html
13c13
<     <link href="../../../tei.css" rel="stylesheet" type="text/css" />
---
>     <link href="../../tei.css" rel="stylesheet" type="text/css" />
diff -r actual-results/testnotes/three.html expected-results/testnotes/three.html
13c13
<     <link href="../../../tei.css" rel="stylesheet" type="text/css" />
---
>     <link href="../../tei.css" rel="stylesheet" type="text/css" />
diff -r actual-results/testnotes/two.html expected-results/testnotes/two.html
13c13
<     <link href="../../../tei.css" rel="stylesheet" type="text/css" />
---
>     <link href="../../tei.css" rel="stylesheet" type="text/css" />
make[1]: *** [test-to-html] Error 1
make: *** [test] Error 2
```

Seems some paths are wrong now?

2020-08-14 10:49 UTC, peterstadler commented
ok, did more testing: the paths are not 'wrong' but reflect the new folder structure that @sydb applied, i.e. the extra path element 'actual-results'.
Running the modified Makefile against the current Stylesheets-dev version of `p5subset.xml` and expected results did not produce any other serious differences so I confirm that @sydb did an excellent job in refactoring the Test-Makefile.

Yet, when I replace the source/p5subset.xml with the current one from https://jenkins.tei-c.org/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/xml/tei/odd/p5subset.xml, I still get the DTD error 
```
<!ELEMENT lem (#PCDATA|_DUMMY_model.divLike|%model.divPart;|titlePage|||_DUMMY_m
                                                                      ^
```

2020-08-14 11:12 UTC, peterstadler requested changes
My final conclusion: The current PR is a refactoring of the Makefile with adjusted tests but it does not solve the problem reported at #454 and #220

2020-08-14 11:12 UTC, peterstadler commented on source/p5subset.xml
> +        <classRef key="model.titlepagePart"/>
@sydb you're cheating and removed the `except="binaryObject graphic"`

2020-08-14 14:12 UTC, hcayless commented on source/p5subset.xml
> +        <classRef key="model.titlepagePart"/>
So, to be fair, it's possible to solve this problem by just pointing directly at the desired elements in `<lem>`'s content model. I was naively assuming that the Stylesheets implemented that feature of Pure ODD. They don't, really.

2020-08-14 14:48 UTC, sydb commented
Sorry I was not available to reply earlier to your comments starting 8 hours ago, @peterstadler; might have been able to help you avoid some of that journey of discovery you went through. Such are time zones. Anyway, thanks for verifying.

2020-08-14 14:52 UTC, sydb commented on source/p5subset.xml
> +        <classRef key="model.titlepagePart"/>
Oh BLEEP!
I must have copied the p5subset we were playing with on Tue morning, not the p5subset from Jenkins or my local dev build. Thank you for catching that, @peterstadler! (No wonder things worked so well. :-)
Yes, @hcayless, our conclusion Tue morning was that this is probably an error in handling a `<classRef>` with `@except`, and thus it could either be fixed (best plan) or worked around by tweaking the ODD (probably what we will have to do for intermediate hack for this release until we can get a real fix).
I hope to look at the `@except` problem starting in perhaps 10 mins.

2020-08-14 15:25 UTC, sydb commented
It seems I am insufficiently savvy with GitHub to figure out how to see the actual change you requested, @peterstadler, but I presume it is to swap in the current p5subset from dev. (Which has a lot more changes than just the missing `@except`.)

I will try to do that in the next hour.

2020-08-14 16:43 UTC, sydb commented
@martindholmes has convinced me that, despite @peterstadler’s heroic efforts, the fact that I (inadvertently) combined an update to p5subset with the changes to the Makefile make this PR too hard to properly review in a timely manner.
Thus I am suggesting we defer full review and pulling of this branch until after release. (I personally plan to use this new Makefile as I work on #455, but that only means there will be different testing on it from me and Jenkins, which is good.)

2020-08-22 16:18 UTC, sydb commented
OK, @martindholmes, and any other requested reviewer (@hcayless, @raffazizzi, @jamescummings, @lb42), I think it would be good for at least 1 other person to verify this works.

Note that what you are testing here is **Tests/Makefile**. You should feel free to swap in whatever p5subset.xml you want (by changing **source/p5subset.xml**, or by setting a default source on the commandline, for exampe `make DEFAULTSOURCE=/home/duck/quack/p5subset.xml`), and to make whatever changes to expected_results/ you want in order to see how the Makefile works. Since the directory structure of the files generated by the Makefile are different (due to new actual_results/ directory) it is a given that some files in expected_results/ will be different, because the path to (e.g.) CSS files is different.

When we actually merge this PR in, there is no reason to merge those files (subset and expected_results/), only the Makefile itself. A separate commit could deal with expected_results/.

It is worth testing both the standard fix-one-file-at-a-time procedure that some of us get frustrated with, and the suggested all-at-once procedure. To see the latter issue `make help`.

2020-08-22 17:27 UTC, martindholmes commented
@sydb The tests work fine, but the p5subset in this branch is way different from the current one in dev, so everything will break when it's merged. I think what should happen is:

1. Pull the current p5subset from the dev branch of P5 into Stylesheets/dev

2. Pull those changes into your branch.

3. Update expected-results etc. as necessary.

4. Merge into dev.

I do like the much more helpful output from a lot of the tests, though!

2020-08-28 23:10 UTC, merged