Addressing `@preserveOrder` for #241
TEIC/Stylesheets pull request #507
Opened 2021-05-22 20:37 UTC by joeytakeda

This batch of commits modifies `odd2odd.xsl`, which was dropping `@preserveOrder` (and all other attributes) on `<sequence>`. There are also some new tests added to Test2 to confirm that `preserveOrder` is reflected in the RNG output.

2022-05-27 17:39 UTC, sydb requested changes
Overall I think this looks excellent. It solves a problem I wish we did not have (I think having `@preserveOrder` with default of "true" on `<sequence>` is a really bad way to do this). But certainly if this is going to work, the attriubtes need to survive. Thus overall I want us to merge in @joeytakeda’s fix, with thanks.
There is, however, 1 logic error in the prose of testPure1InvalidInstance.xml that needs to be fixed first, lest it confuse future readers out of their minds.

2022-05-27 17:39 UTC, sydb commented on Test2/inputFiles/invalidInstances/testPure1InvalidInstance.xml
> +        <p>This <choice><reg>test</reg><orig>Test</orig></choice> should be invalid, as <gi>reg</gi> ought to appear
Umm, no.
This should be invalid because the `<orig>` ought to appear before the `<reg>`.

2022-05-27 17:39 UTC, sydb commented on odds/odd2odd.xsl
> +    <xsl:variable name="otherAtts" select="@*[not(local-name() = ('minOccurs','maxOccurs'))]"/>
I would much prefer to test the nodes, rather than their names. I.e.
~~~xml
<xsl:variable name="otherAtts" select="@* except ( @minOccurs, @maxOccurs )"/>
~~~

2022-05-27 17:39 UTC, sydb commented on odds/odd2odd.xsl
> +            <!--joeytakeda iss241: I'm not sure if the @* below is necessary -->
I think not only are you correct, @joeytakeda, you are so correct that in the old days I would have suggested that, rather than add this comment, you should just delete the "@*|" from the `@select` which is now on line 1499. Nowadays, though, there are those among us who thing we should _not_ fix _other_ things on any given PR.

2022-05-27 17:49 UTC, joeytakeda commented
Thanks, @sydb — agreed on all fronts here. I'll make those changes now.

2022-05-28 03:47 UTC, sydb approved these changes
I ran this through both Test2/ and Test/ tests (except the xelatex test, which will not run on my system). Passed them all. This should be merged, IMHO. (Despite the fact that I don’t _like_ this way of handling unordered, but required children.)

2022-07-01 16:40 UTC, sydb commented
@joeytakeda For reasons I do not understand, some of the tests in Test/ are now failing. I have both fixed them in a commit to this repo on my local machine, and @HelenaSabel and I have changed the Test/Makefile program so that these should not cause errors in the future. (Simultaneously making the test slightly weaker.)
So could you either
1. Give me r/w permission to this repo, or
2. Merge in the latest from the upstream TEIC/Stylesheets:dev branch into here, and try re-running the tests yourself.
Thanks.

2022-07-07 18:38 UTC, joeytakeda commented
Hi @sydb I've merged the changes from TEIC/Stylesheets:dev into the branch and both `make test` and `make test2P` are successful locally (the tests have failed here, but I think that's just because of the Slack webhook?)

2022-07-17 00:39 UTC, sydb commented
@joeytakeda — Sorry, did not notice your reply of 9 days ago. (And I even left this tab open in my browser for 2 weeks just so I would see it! Sigh.)

This passes all tests on my local system (except [this bug](#562) interfered), except for whitespace in the test30.rnc output. So I think it should be merged right away, before more divergence occurs. (And we can fix the test30 output after it is merged.)

Oh. It is assigned to me. So I will merge it now, and hope to fix the test30 problem within an hour.

2022-07-17 00:40 UTC, merged