Allow the `<ref>` elements to get processed:
TEIC/Stylesheets pull request #542
Opened 2022-01-28 16:54 UTC by sydb

Stylesheets group, with big thanks to @hcayless, realized
a) these things (contents of `<hi>` in intermediate Lite stage that contain the `<ref>`s that were not working) were being processed with `<value-of>`, not `<apply-templates>`; and
b) furthermore, the templates for `<ref>` would have been processed if these templates for `<hi>` did not exist, and since all they were doing in 2 of 3 cases was adding boldface we did not like (and failing to process the `<ref>`s), we just nuked 2 of them and fixed the 3rd (which also adds the pointy brackets for element names).

We tested this once, in a Docker container, and it seemed to work. If one of either @peterstadler, @martindholmes, or @npcole can reproduce that this works (by generating PDF and looking at the list of macro names in section 1.4.1 “Standard Content Models” on page 16 of the PDF, and ensuring they _are_ working links, and also looking around elsewhere in the PDF _Guidelines_ and making sure we didn’t break anything else), then I think one of the other two can just merge it.

2022-01-28 17:24 UTC, martindholmes commented
@sydb I just checked out the branch and ran a build (make clean pdf), and I do indeed see links in the 1.4.1 section where they did not exist before. I can't find any other changes or regressions. I think this is working as intended. I think if either @peterstadler or @npcole also see the same result, they should merge the PR.

2022-04-12 14:41 UTC, peterstadler commented
I fear the change is too simple. Compare the current dev output
![current dev output](https://user-images.githubusercontent.com/2247936/162987184-84faecb4-7bc5-4c3a-ba92-00043dc89780.png)
and the output of this branch
![branch sydb_issue_537](https://user-images.githubusercontent.com/2247936/162987410-f435d837-7a0a-47e9-8c31-1cea18326b93.png)

There's at least two issues:
1. The square brackets are missing to signal to LaTeX the custom item label (in a LaTeX list)
2. the angle brackets are not part of the hyperlink (which they usually are)

2022-04-12 14:52 UTC, peterstadler requested changes
A third issue is the removal of the bold face. Was that done on purpose?

2022-04-12 14:54 UTC, peterstadler commented
> A third issue is the removal of the bold face. Was that done on purpose?

I just reminded myself to read the original message and found the answer there :)

2022-04-12 15:09 UTC, sydb commented
I think @peterstadler raises absolutely valid concerns that should be addressed. That said, I think the output from this branch is still better than that from the current released branch. So I would be inclined to merge this and generate a new ticket to fix the LaTeX square bracket and pointy-brackets-in-link issues. (And perhaps have a larger discussion as to whether the boldface should stay or go.) That said, if others disagree, we can just not merge this puppy now and fix those issues here.

2022-04-12 15:10 UTC, peterstadler commented
I'm already having a look and hope to provide the required fixes asap

2022-04-14 06:40 UTC, peterstadler commented
Sorry, I *might* only get at it this weekend. My idea is to keep the old switch cases, remove the `\textbf` since you don't like it, and call `makeInternalLink` (instead of simply `value-of`). 
I think there's not much markup that would be missed (by not calling `apply-templates`) but the links could be added (including the angle brackets for element names). If someone wants to try this, please feel free!

2022-04-16 07:29 UTC, peterstadler commented
Here's the updated output:
![Bildschirmfoto 2022-04-16 um 09 15 53](https://user-images.githubusercontent.com/2247936/163666014-401eeab3-ca70-4d76-89bb-0d6d887096f2.png)
![Bildschirmfoto 2022-04-16 um 09 16 37](https://user-images.githubusercontent.com/2247936/163666017-d1e20542-604a-4fb5-930d-8e72b674f156.png)

Links are there, indent level is right. A quick diff of the tex files revealed only intended changes, e.g. changing from 
```tex
\item [\textbf{<s>}] (s-unit) contains a sentence-like division of a text.
```
to 
```tex
\item [{\hyperref[TEI.s]{<s>}}] (s-unit) contains a sentence-like division of a text.
```

Yet, I'm still not sure whether I like the un-bolding of those labels.

2022-04-16 16:22 UTC, peterstadler commented
May I ask @martindholmes and @npcole to review. I think this is an improvement and could go into the release

2022-04-16 16:36 UTC, martindholmes commented
@peterstadler Definitely an improvement, and should go into this release. I say yes to merge.

2022-04-16 16:38 UTC, martindholmes approved these changes
Looks good. Go from me.

2022-04-16 22:15 UTC, sydb commented
Will test & merge as soon as set with release-blocker …

2022-04-18 14:43 UTC, merged