XLSX→TEI drops empty cells, the PR
TEIC/Stylesheets pull request #587
Opened 2022-12-02 01:41 UTC by sydb

I merely implemented the fix @GVogeler outlined on [the ticket](#323). Seems to work. Fix did the right thing with the test data he attached to that ticket, and both Test and Test2 pass. However, I do not think there is anything in either test process that actually exercises XLSX→TEI. Sigh.

2022-12-02 08:41 UTC, peterstadler requested changes
The Debian changelog file was probably committed by accident. Could you please undo this change to remedy the conflict?

2022-12-02 14:11 UTC, sydb commented
In principle I am more than happy to. In practice, I do not know how off the top of my head, and will have to fight with git for a bit …

2022-12-07 19:25 UTC, HelenaSabel approved these changes
I think I fixed the conflict so I would say that the PR is ready to merge.

`Test` does include a XLSX to TEI transformation (which didn’t break with these changes). I wonder if a third sheet should be added to `Test/test.xlsx` with some empty cells.

2022-12-08 08:25 UTC, peterstadler approved these changes

2023-01-26 20:03 UTC, merged