ignore `@version` of `<application>` when comparing in tests
TEIC/Stylesheets pull request #650
Opened 2023-11-20 22:11 UTC by sydb

I could not just delete `@version` (as was my original plan), because in at least 1 place the output is validated between generation and comparison, and it turns out `@version` is required. Harumph. So the "cleanForDiff" target in Test2/ and the cleanup.pl pgm in Test/ now change it to a ridiculous, but valid, value.

2023-11-30 16:06 UTC, raffazizzi requested changes

2023-11-30 16:06 UTC, raffazizzi commented on Test2/cleanForDiff.xsl
> +		5. Remove the @version attribute of &lt;application> elements that have
Perhaps this should say "Replace with a placeholder the value of the @version attribute on &lt;application> elements that..."

2023-11-30 16:06 UTC, raffazizzi commented on debian-tei-xsl/debian/changelog
This doesn't seem related to the PR, right? It may need to stay here, though, unless you want to re-do the PR; I don't think there's an easy way to remove one file from a pushed commit.

2024-01-25 22:10 UTC, sydb commented on debian-tei-xsl/debian/changelog
I have no understanding of why this file pops into our change set intermittently. IIRC @hcayless just said to ignore it, so I do.

2024-01-25 22:19 UTC, sydb commented on Test2/cleanForDiff.xsl
> +		5. Remove the @version attribute of &lt;application> elements that have
I have pushed a complete re-wording of that list item.

2024-01-26 14:58 UTC, raffazizzi approved these changes

2024-01-26 14:58 UTC, merged