Fixes #657
TEIC/Stylesheets pull request #682
Opened 2024-05-06 03:20 UTC by joeytakeda

Adds another rule to odd.css to ensure colon and space

2024-07-07 15:38 UTC, ebeshero commented
@sydb @martinascholger @HelenaSabel  I think we just lost track of this work that @joeytakeda did in May to improve the output CSS of generated ODDs. I just updated the branch and the tests are passing. (I'm not suggesting we merge it for the imminent release, but we may want to continue working on CSS for custom ODD-generated HTML on this branch, and merge for the next release?)

2024-07-07 16:39 UTC, HelenaSabel commented
@ebeshero: I will be partial to merge the current work as it is after the release (if @joeytakeda agrees). In principle, the current generation of ODD documentation will be superseded relatively soon so I wonder if it isn’t better to work on issues with higher priority.

2024-07-10 02:13 UTC, sydb requested changes
I did not investigate _why_, but with this PR there is not just a “: ” after the classname before the list of attributes, there is a “ : ”. (That is, space-colon-space instead of just colon-space.)

2024-11-25 20:26 UTC, joeytakeda commented
> I did not investigate _why_, but with this PR there is not just a “: ” after the classname before the list of attributes, there is a “ : ”. (That is, space-colon-space instead of just colon-space.)

I'm not sure what you were seeing here, @sydb — in looking at the changes, I only see colon+space not space+colon+space.

2024-11-25 22:15 UTC, sydb commented
Well, I cannot at the moment reproduce the problem I was seeing before, thus approving. (Not sure why this is a draft PR — as far as I am concerned it can be merged.)

2024-11-25 22:15 UTC, sydb approved these changes

2025-03-18 19:38 UTC, merged