handle `<constraintDecl>` from extract-isosch.xsl
TEIC/Stylesheets pull request #698
Opened 2024-09-20 23:26 UTC by sydb

Addresses issue #696.
Process new `<constraintDecl>` element: use its `@queryBinding` attr, copy over its `<sch:ns>` elements into the declared NS section, and all other child elements into a new declarations section.

2024-09-23 04:51 UTC, joeytakeda requested changes

2024-09-23 04:51 UTC, joeytakeda commented on odds/extract-isosch.xsl
> +      <xsl:for-each select="$NSs[ not( . eq '␝'  or  contains( ., $xsl-ns ) ) ]">
The comment here seems slightly inaccurate, since this is saying all of the `$NSs` except the ones that are equal to the group separating character (␝)(https://www.compart.com/en/unicode/U+241D)or that _contain_ the XSL namespace. I would assume this means that empty ones could conceivably make it through?

2024-09-23 04:51 UTC, joeytakeda commented on odds/extract-isosch.xsl
> +    <xsl:variable name="qb" select="( //tei:constraintDec[ @scheme eq 'schematron']/@queryBinding, 'xslt2')[1]"/>
Typo here, I think — missing the final `l` on constraintDecl

2024-09-23 16:26 UTC, sydb commented on odds/extract-isosch.xsl
> +      <xsl:for-each select="$NSs[ not( . eq '␝'  or  contains( ., $xsl-ns ) ) ]">
Uhhh … No to the ultimate question, but maybe phrasing and test should be a little more precise, here.
An “empty” one, i.e. (presumably) an element that has been decorated with both an empty `@nsp` and an empty `@nsu` would end up being the single character `␝`, and thus match the first comparison.
The contains() is meant to ensure that we do not generate a `<sch:ns>` for the XSLT namespace here in the implicit section. (I am not sure why we are worried about it — would it hurt anything if it were generated?) But of course it is not testing equality, so in fact if someone (bizarrely) had a namespace URI of “this-is-not-http://www.w3.org/1999/XSL/Transform_NOT”, this test would incorrectly see it as the XSLT namespace and fail to generate the needed `<sch:ns>`. So I think that should be updated to `matches( ., '␝'||$xsl-ns||'$')`.

2024-09-23 17:36 UTC, sydb commented on odds/extract-isosch.xsl
> +    <xsl:variable name="qb" select="( //tei:constraintDec[ @scheme eq 'schematron']/@queryBinding, 'xslt2')[1]"/>
Fixed, thank you, good catch.

2024-10-15 22:04 UTC, joeytakeda approved these changes

2024-10-18 10:36 UTC, merged

2024-10-18 10:37 UTC, tuurma commented
Thanks @sydb and @joeytakeda, merging!