fix #703: update link in README.md
TEIC/Stylesheets pull request #710
Opened 2024-11-06 09:17 UTC by rettinghaus

This updates the link to the Guidelines.
Closes #703

2024-11-09 23:48 UTC, sydb reviewed
Well, you are absolutely correct that …/Guidelines/P5/get.xml is a dead link. (And thanks for fixing the notation on line 21, too.) The problem is that …/guidelines/p5/ is not the right link.

I do not know what is the right, though. I think get.xml used to forward to …/guidelines/p5/using-the-tei-github-repository/, but I do not know what file in our current repos that might have been. (I have tried searching on my local HD without useful results.) Maybe @hcayless, @martinascholger, or @jamescummings can help?

2024-12-05 01:16 UTC, ebeshero requested changes
Commenting here to review with Council before implementing an update.

2024-12-05 01:16 UTC, ebeshero commented on README.md
> +It is helpful to have the TEI environment installed locally. Please refer to <https://tei-c.org/guidelines/p5/> for hints on how to do that.
There's another broken link pointing to get.xml in [TCW 32](https://tei-c.org/documentation/tcw32/), but there the broken link is titled "Using the TEI GitHub Repository", so it seems likely to be, really, this page on the old TEI website: https://old.tei-c.org/guidelines/p5/using-the-tei-github-repository/  Much of the contents are relevant (like most of the make targets listed), but that page really seems outdated--particularly the content on Roma (mainly about old Roma and mentioning our new Roma as still under development). I'd like to propose a new ticket to rewrite it. 

Meanwhile, I recommend revising the phrasing and providing a couple of links (at least for now). How about this revision to update our advice?

To work with the Stylesheets, you can:
* Install the TEI environment locally: Somewhat dated information on this is available at  [Using the TEI GitHub Repository](https://old.tei-c.org/guidelines/p5/using-the-tei-github-repository/)
* (Recommended): avoid the local installation and work with the up-to-date pre-built test environment in Docker, described in <https://tei-c.org/documentation/tcw32/>

2024-12-05 01:16 UTC, ebeshero commented on README.md
> +It is helpful to have the TEI environment installed locally. Please refer to <https://tei-c.org/guidelines/p5/> for hints on how to do that.
I don't like linking to an old page on the TEI website on our README, so I have opened [a new ticket](https://github.com/TEIC/Stylesheets/issues/720) recommending that we update the old Using the TEI GitHub Repository page and establish it on the new website.

2024-12-11 14:05 UTC, rettinghaus commented on README.md
> +It is helpful to have the TEI environment installed locally. Please refer to <https://tei-c.org/guidelines/p5/> for hints on how to do that.
@ebeshero I updated the PR with your proposal, which should be fine now until #720 has been addressed.

2025-07-29 17:26 UTC, merged

2025-07-29 17:26 UTC, ebeshero commented
We're not finished with this yet, but Stylesheets group agrees this is an important step to update what we have.